const list = [
    {
      id: 1,
      title: "pencil box",
      author: "Made in India | 25 november 2023",
      price: 100,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAdhks8oOdLV2zTO3jv7T_UBIjTb6TYvKKyA&usqp=CAU",
      amount: 1,
    },
    {
      id: 2,
      title: "Apsara Pencil",
      author: "Hindustan Universal Limited | 1 September 2023",
      price: 98,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuo5xcJz8wSEcTaYYpBAyE4tJc6x6i4ydJcRk5or2m0q_Cra7K7GB3SK-hUs06Z6-p6As&usqp=CAU",
      amount: 1,
    },
    {
      id: 3,
      title: "Geomentry Box",
      author: "ClassMate | Made in India",
      price: 143,
      img: "https://syacaa.com/wp-content/uploads/2020/02/1.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "WaterBottle",
      author: "Korean water bottles | Made in Korea",
      price: 57,
      img: "https://i.pinimg.com/originals/bd/f2/94/bdf2949ee90cecde55fadbd3dfa2af9c.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Backpack Bags",
      author: "Cute Bags | light Pink",
      price: 149,
      img: "https://img.fruugo.com/product/3/23/666092233_max.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Spiral Note",
      author: "Classmate Spiral Note| For School/College/Office",
      price: 135,
      img: "https://images.jdmagicbox.com/quickquotes/images_main/classmate_pulse_6_sub_spiral_notebook_2100114__11926272_0.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Notepad",
      author: "Fancy Notepads|Kawai shop ",
      price: 693,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcwNg5dJbtokyvI5kxxQcfsZhChgKbjYlVeA&usqp=CAU",
      amount: 1,
    },
    {
      id: 8,
      title: "Ink Pens",
      author: "Colorfull Ink Pens | Reusable Pens",
      price: 289,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoVMaVNStaqOmJGmck12IgoG_ZbxGYc9Voy1A7qcxwRatY6TtnEEu5APKC1e28Nv7BMys&usqp=CAU",
      amount: 1,
    },
    {
      id: 9,
      title: "Pens ",
      author: "Cute Korean Pens",
      price: 80,
      img: "https://img.fruugo.com/product/5/11/540158115_max.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Water Bottle Kit",
      author: "Siper bottles | Cute Colors",
      price: 86,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0aS_srv0F-IALYEhOIoQfrog2JNJPfCJ3zA&usqp=CAU",
      amount: 1,
    },
    {
      id: 11,
      title: "Painting Kit",
      author: "For Kids| Colouring World",
      price: 120,
      img: "https://m.media-amazon.com/images/I/51bB+dW-pEL._AC_SS300_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Stationary kit",
      author: "Unicorn | Beautiful Kit",
      price: 157,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2p3Dur_kLdM9BbfCXTNvMWvRln-ZyJOSXDg&usqp=CAU",
      amount: 1,
    },
  ];
  export default list